# Generated by Django 3.2.23 on 2023-11-09 16:59

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('manager_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('rated', models.IntegerField(choices=[(0, 'G'), (1, 'PG'), (2, 'PG-13'), (3, 'NC-17'), (3, 'R')])),
                ('year', models.IntegerField()),
                ('director', models.CharField(blank=True, max_length=255)),
                ('genre', models.CharField(blank=True, max_length=255)),
                ('distribution', models.CharField(blank=True, max_length=255)),
                ('actors', models.CharField(blank=True, max_length=255)),
                ('poster', cloudinary.models.CloudinaryField(max_length=255)),
                ('discreption', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('manager', models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
