# Generated by Django 3.2.23 on 2023-11-09 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='manager',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
