# Generated by Django 3.2.23 on 2023-11-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='../default_profile_br7153', upload_to='images/'),
        ),
    ]
