# Generated by Django 3.2.23 on 2023-11-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='../default_post_jneohh', upload_to='images/'),
        ),
    ]
