# Generated by Django 3.2.23 on 2023-11-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20231113_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='start_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
