# Generated by Django 3.2.23 on 2024-01-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='session_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
