# Generated by Django 3.2.23 on 2024-01-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movie_session_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='session_time',
            field=models.TimeField(blank=True),
        ),
    ]
