# Generated by Django 3.2.23 on 2024-01-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_movie_session_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
