# Generated by Django 3.2.23 on 2024-01-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20240103_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, default='../default_post_jneohh', upload_to='images/'),
        ),
    ]
