# Generated by Django 3.2.23 on 2024-01-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='../default_post_jneohh', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rated',
            field=models.IntegerField(choices=[(0, 'G'), (1, 'PG'), (2, 'PG-13'), (3, 'NC-17'), (3, 'R')], default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='session_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
