# Generated by Django 3.2.23 on 2023-11-13 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(84), django.core.validators.MinValueValidator(1)]),
        ),
    ]
