# Generated by Django 3.2.23 on 2024-01-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='show_date',
            field=models.DateField(),
        ),
    ]
