# Generated by Django 3.2.23 on 2024-01-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_show_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='show_date',
            field=models.DateTimeField(),
        ),
    ]
